#!/bin/sh
if [ $# -eq 0 ]
 then gvim -n -i NONE -u NONE "+colo peachpuff" "+se guifont=Monospace\ 15 go= lines=99 co=999 hid clipboard=unnamedplus hls ai enc=utf-8 nocompatible nu backspace=indent,eol,start" "+syntax on"
 else gvim -n -i NONE -u NONE "+colo peachpuff" --remote-silent "+se guifont=Monospace\ 15 go= lines=99 co=999 hid clipboard=unnamedplus hls ai enc=utf-8 nocompatible nu backspace=indent,eol,start" "+syntax on" "$@"
fi
